from setuptools import setup, find_packages

setup(
    name="DaeFinder",
    version="v0.3.0",
    description="A Python package to discover Differential Algebraic Equations from data.",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/mjayadharan/DAE-FINDER_dev",
    author="Manu Jayadharan",
    author_email="manu.jayadharan@gmail.com",
    license="MIT",
    packages=find_packages(),
    install_requires=[
        "numpy",
        "scipy",
        "pandas",
        "sympy",
        "scikit-learn",
        "matplotlib",
        "joblib",
    ],
    classifiers=[
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Programming Language :: Python :: 3.13",
        "Programming Language :: Python :: 3.14",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires=">=3.9",
)
